---
# tasks file for logstash-role

- include: logstash_requirements.yml
  tags:
   - logstash_req
   - logstash

- name: Stop Logstash before upgrading
  service: name=logstash
           state=stopped
  ignore_errors: yes
  tags:
    - logstash

- include: logstash_installation_Debian.yml
  when: ansible_os_family == "Debian"
  tags:
    - logstash

- include: logstash_installation_RedHat.yml
  when: ansible_os_family == "RedHat"
  tags:
    - logstash

- include: logstash_plugins.yml
  when: logstash_plugins is defined
  tags:
   - logstash_plugins
   - logstash

- include: logstash_configuration.yml
  tags:
   - logstash_conf
   - logstash

- name: Defining input for system logs
  when: logstash_system_logs
  template: src=system.conf.j2 dest="{{ logstash_conf_dir }}/system.conf" owner=root group=root mode=0644
  notify:
    - restart logstash
  tags:
    - logstash

- name: "Defining logstash input for logstash's own logs!"
  template: src=logstash_on_logstash.conf.j2 dest="{{ logstash_conf_dir }}/logstash.conf" owner=root group=root mode=0644
  when: logstash_on_logstash
  notify:
    - restart logstash
  tags:
    - logstash

- name: Start Logstash
  service: name=logstash
           state=started
           enabled=yes
  tags:
    - logstash
